# Generated by Django 5.0.6 on 2024-07-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_remove_course_imageurl_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(choices=[(1, 1), (11, 11), (21, 21), (31, 31), (41, 41), (51, 51), (61, 61), (71, 71), (81, 81), (91, 91)], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='isHome',
            field=models.BooleanField(default=True),
        ),
    ]
